Department.create!([
  {name: "New Mexico Motor Transportation Police Department", city: "Tularosa", county: "Otero", state: "NM", level: "state", notes: nil},
  {name: "Rio Arriba County Sheriff's Office", city: "Española", county: "Rio Arriba", state: "NM", level: "county", notes: nil},
  {name: "Mt. Juliet Police Department", city: "Mt. Juliet", county: "Wilson", state: "TN", level: "city", notes: nil},
  {name: "California Highway Patrol", city: "", county: "", state: "CA", level: "state", notes: nil},
  {name: "City of Pittsburgh Bureau of Police", city: "Pittsburgh", county: "Allegheny", state: "PA", level: "city", notes: nil},
  {name: "Fulton Police Department", city: "Fulton", county: "Oswego", state: "NY", level: "city", notes: nil},
  {name: "fart", city: "", county: "", state: "", level: "federal", notes: nil},
  {name: "ref2", city: "", county: "", state: "", level: "federal", notes: nil},
  {name: "ref3", city: "", county: "", state: "", level: "federal", notes: nil},
  {name: "Philadelphia Police Department", city: "Philadelphia", county: "Philadelphia", state: "PA", level: "city", notes: nil},
  {name: "Los Angeles County Sheriff's Department", city: "Los Angeles", county: "Los Angeles", state: "CA", level: "county", notes: nil},
  {name: "Vermont State Police", city: "Waterbury", county: "Washington", state: "VT", level: "state", notes: nil},
  {name: "Memphis Police Department", city: "Memphis", county: "Shelby", state: "TN", level: "city", notes: nil},
  {name: "Fort Wayne Police Department", city: "Fort Wayne", county: "Allen", state: "IN", level: "city", notes: nil},
  {name: "Collingdale Police Department", city: "Collingdale", county: "Delaware", state: "PA", level: "city", notes: nil},
  {name: "Denver Police Department", city: "Denver", county: "Denver", state: "CO", level: "city", notes: nil},
  {name: "Portland Police Bureau", city: "Portland", county: "Multnomah", state: "OR", level: "city", notes: nil},
  {name: "Galveston Police Department", city: "Galveston", county: "Galveston", state: "TX", level: "city", notes: nil},
  {name: "Detroit Police Department", city: "Detroid", county: "Wayne", state: "MI", level: "city", notes: nil},
  {name: "Wewoka Police Department", city: "Wewoka", county: "Seminole", state: "OK", level: "city", notes: nil},
  {name: "North Augusta Police Department", city: "North Augusta", county: "Aiken", state: "SC", level: "city", notes: nil},
  {name: "Mt Rainier Police Department", city: "Mt. Rainer", county: "Prince George's", state: "MD", level: "city", notes: nil},
  {name: "Iowa State Patrol", city: "Des Moines", county: "Polk", state: "IA", level: "state", notes: nil},
  {name: "Sorrento Police Department", city: "Sorrento", county: "Ascension", state: "LA", level: "city", notes: nil},
  {name: "Naperville Police Department", city: "Naperville", county: "DuPage", state: "IL", level: "city", notes: nil},
  {name: "Oklahoma Highway Patrol", city: "Lawton", county: "Comanche", state: "OK", level: "state", notes: nil},
  {name: "Orlando Police Department", city: "Orlando", county: "Orange", state: "FL", level: "city", notes: nil},
  {name: "Seabrook Police Department", city: "Seabrook", county: "Harris", state: "TX", level: "city", notes: nil}
])
Incident.create!([
  {uuid: "0f507cf3-6c81-4e06-bc21-e6f069abb4b7", incident_summary: "10-year-old boy is tasered by a police officer for refusing to wash the police officer's car. The lawsuit claims police officers drove their patrol cars onto the intermediate school campus, where Webb asked a group of boys which one would like to clean his patrol unit. R.D. raised his hand to say he did not want to clean the police officer’s car.\r\nWebb then said, according to the lawsuit, “Let me show what happens to people who do not listen to the police.”  He then “shot his Taser gun at the boy’s chest,” said the family’s attorney Shannon Kennedy of the Kennedy Law Firm of Albuquerque.", incident_year: 2012, incident_month: 5, incident_day: 12, reported_year: 2012, reported_month: 11, reported_day: 2, location_state: "NM", location_city: "Tularosa", location_county: nil, location_zip: "88352", location_notes: "Tularosa, N.M., Intermediate School.", context: "other", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 1, officer_count: nil, officer_multiple_incident: nil},
  {uuid: "b9fc72a0-8bff-4325-a40d-b8a6e4b250f8", incident_summary: "Off duty cop pulls his gun on a man and hits him in the face with his badge.", incident_year: 2014, incident_month: 3, incident_day: nil, reported_year: 2014, reported_month: 9, reported_day: 26, location_state: "NM", location_city: "Albuquerque", location_county: nil, location_zip: "871", location_notes: "", context: "other", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "When they reached a dead end, the sheriff jumped out holding his gun, dragged Tafoya into the street and struck him in the face with his badge, prosecutors said.\r\n\"I said, 'Please, don't kill me,' \" Tafoya testified.\r\n\"It's too late. It's too late,\" Rodella replied, according to Tafoya.\r\n", outcome_dollars: nil, department_id: 2, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "210e85f9-6fca-425d-ba25-002f57c21fcd", incident_summary: "Officer pulls a woman over for having expired tabs (she didn't) but really used it as an excuse to meet the woman. Turns off his dash cam and mic then contacts her several times after the stop presumably looking for a date.", incident_year: 2014, incident_month: 8, incident_day: nil, reported_year: 2014, reported_month: 9, reported_day: 17, location_state: "TN", location_city: "Mt. Juliet", location_county: nil, location_zip: "3712", location_notes: "", context: "traffic-stop", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: false, abuse_intimidation: true, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 3, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "4afd6810-ae5d-435d-a3a6-dc49a6c63b9b", incident_summary: "Officer straddles woman on the side of the highway and beats her repeatedly in the heat and face.", incident_year: 2014, incident_month: 7, incident_day: 1, reported_year: 2014, reported_month: 7, reported_day: 1, location_state: "CA", location_city: "Los Angeles", location_county: nil, location_zip: "900", location_notes: "", context: "911", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: 1500000, department_id: 4, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "941dbd94-44de-4e61-b6e2-614bb2b1e337", incident_summary: "Man was praying over his dead son in hospital when officers tased him and took him into custody.", incident_year: 2014, incident_month: 6, incident_day: 24, reported_year: 2014, reported_month: 9, reported_day: 25, location_state: "PA", location_city: "Pittsburgh", location_county: nil, location_zip: "152", location_notes: "Mercy Hospital", context: "other", victim_count: 1, victim_animal: false, victim_notes: "Earl Baldwin Jr", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 5, officer_count: 5, officer_multiple_incident: nil},
  {uuid: "785c984e-727c-4188-a265-59b167206930", incident_summary: "A decorated veteran police sergeant has pleaded guilty to beating a handcuffed man and now faces up to 10 years in prison. The DOJ said Arigo walked into the room were Bloss was being held and \"shoved his head into the bench, and punched him in the head multiple times.\" Arigo also pulled the video camera out of the wall to stop it from recording, the DOJ said.", incident_year: 2014, incident_month: 6, incident_day: 28, reported_year: 2014, reported_month: 9, reported_day: 24, location_state: "NY", location_city: "Fulton", location_county: nil, location_zip: "13069", location_notes: "Beating happened while at the police station", context: "other", victim_count: 1, victim_animal: false, victim_notes: "Gary E. Bloss.", abuse_force: true, abuse_search: false, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 6, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "e97fbfc0-ea37-41e9-a1e6-3072e8ca43a1", incident_summary: "Officers put a man into a van and then drive recklessly (probably on purpose) resulting in severe injuries. Officers then lie on the witness stand and have their testimony refuted by expert witness. ", incident_year: 2011, incident_month: 6, incident_day: 23, reported_year: 2014, reported_month: 9, reported_day: 27, location_state: "PA", location_city: "Phillidelphia", location_county: nil, location_zip: "191", location_notes: "Center City neighborhood", context: "911", victim_count: 1, victim_animal: false, victim_notes: "James McKenna", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: true, abuse_notes: "McKenna was then handcuffed and put in the van, but not strapped in. He said police accelerated and decelerated the wagon, knocking him to the floor four times. McKenna’s injuries included three broken neck vertebrae and two ruptured neck discs. The case was so inundated with lies however, that none of the officers could get their stories straight so there were also reports stating that he “hit [his] head on police car door” and that “while being transported, pt. hit his own head against divider as reported by arriving officers.” As part of the lawsuit, Thomas J. Gibbons, McKenna’s lawyer, presented an expert opinion from a doctor who said McKenna’s injuries were far too serious to have been self-inflicted.", outcome_dollars: 490000, department_id: 10, officer_count: nil, officer_multiple_incident: nil},
  {uuid: "2ce22d0c-fec4-41b9-a098-a68f52042788", incident_summary: "Officer seizes and tows victims car despite not having probable cause for a search and leaves the victim on the side of the road in the winter", incident_year: 2014, incident_month: 3, incident_day: 6, reported_year: 2014, reported_month: 9, reported_day: 20, location_state: "VT", location_city: "Wallingford", location_county: nil, location_zip: "05773", location_notes: "", context: "traffic-stop", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: true, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "Police left Zullo on the side of the road, 8 miles from home, with his hooded sweatshirt to keep warm. “When Mr. Zullo asked (Hatch) why he had to pay for the tow, (Hatch) told him that the tow cost was Mr. Zullo’s fault for exercising his rights,” the complaint states.", outcome_dollars: nil, department_id: 12, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "90dbdbbd-85bf-4110-a204-758d07957526", incident_summary: "4 Memphis police officers were recently suspended after they tipped over a portable toilet that had a human being inside.  31-year-old Joseph Hampton was allegedly being chased by police when he ducked into a construction site and hid in one of the toilets.\r\nRead more at http://thefreethoughtproject.com/4-cops-fired-tipping-portable-toilet-man/#WcqxoQA3bHH8GMFA.99", incident_year: 2014, incident_month: 9, incident_day: nil, reported_year: 2014, reported_month: 9, reported_day: 26, location_state: "TN", location_city: "Memphis", location_county: nil, location_zip: "381", location_notes: "", context: "911", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "Officers exercised excessive force in turning over the portable toilet the man was hiding in.", outcome_dollars: nil, department_id: 13, officer_count: 4, officer_multiple_incident: nil},
  {uuid: "9968e457-c49c-46d9-8392-eed5e1e87c11", incident_summary: "Officer raped a drunk woman he had pulled over.", incident_year: 2013, incident_month: 9, incident_day: nil, reported_year: 2013, reported_month: 9, reported_day: 16, location_state: "IN", location_city: "Fort Wayne", location_county: nil, location_zip: "468", location_notes: "", context: "traffic-stop", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: true, abuse_restrained: false, abuse_notes: "felony counts of sexual misconduct, official misconduct and rape of a victim mentally disabled such that consent was not possible in August as part of a plea agreement", outcome_dollars: nil, department_id: 14, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "925a48ab-c403-443e-af7d-ed64111d5de1", incident_summary: "Police enter citizen's home and confiscate property without a warrant or probable cause. Officers were upset that they were being recorded on the victim's property. Officers then arrest 2 people and threaten to use taser on one of them.", incident_year: 2014, incident_month: 2, incident_day: 22, reported_year: 2014, reported_month: 9, reported_day: 24, location_state: "PA", location_city: "Collingdale", location_county: nil, location_zip: "19023", location_notes: "", context: "911", victim_count: 3, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: true, abuse_misconduct: true, abuse_intimidation: true, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 15, officer_count: 3, officer_multiple_incident: nil},
  {uuid: "3e937d5f-7601-473a-b1ac-60bbdaeb1dfc", incident_summary: "Police force entry into a home without a warrant and physically assault family members looking for drugs. Officers claimed they were let in voluntarily and then people started swinging at them, but those claims did not hold up in court.", incident_year: 2009, incident_month: 1, incident_day: 20, reported_year: 2011, reported_month: nil, reported_day: nil, location_state: "CO", location_city: "Denver", location_county: nil, location_zip: "80204", location_notes: "1263 stuart street denver co\r\n39.736078, -105.043071", context: "other", victim_count: 4, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: true, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: 1800000, department_id: 16, officer_count: nil, officer_multiple_incident: nil},
  {uuid: "85f0b262-707c-497e-a7c2-16ba55029921", incident_summary: "Portland police use excessive force in arresting a man for Driving Under the Influence. Didn't look too bad to me, but a jury awarded $500,000 so clearly some people think something went too far.", incident_year: 2011, incident_month: 6, incident_day: 18, reported_year: 2014, reported_month: 9, reported_day: 29, location_state: "OR", location_city: "Portland", location_county: nil, location_zip: "97236", location_notes: "45.497847, -122.523545", context: "traffic-stop", victim_count: 1, victim_animal: false, victim_notes: "Jason Cox", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: 562000, department_id: 17, officer_count: 3, officer_multiple_incident: nil},
  {uuid: "025d7c29-811f-474c-a55d-3b287b7b48d6", incident_summary: "Plain clothes police officers jump out of a van and try to pull a 12-year-old girl into their van. When she resisted, they beat her up. Later arrested her at school for resisting arrest (after she got out of the hospital)", incident_year: 2006, incident_month: 8, incident_day: 22, reported_year: 2007, reported_month: nil, reported_day: nil, location_state: "TX", location_city: "Galveston", location_county: nil, location_zip: "7755", location_notes: "", context: "911", victim_count: 1, victim_animal: false, victim_notes: "Dymond Larae Milburn", abuse_force: true, abuse_search: false, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "Officers arrested the girl even after her father identified her as his daughter and not a prostitute. Later arrested her for resisting their initial arrest.", outcome_dollars: nil, department_id: 18, officer_count: 3, officer_multiple_incident: nil},
  {uuid: "0808e421-f880-4157-bd2e-3dafee41b612", incident_summary: "Police stop two men in a restaurant and ask for ID without reasonable suspicion of a crime. Then get in a brawl and arrest the men for refusing.", incident_year: 2014, incident_month: 5, incident_day: nil, reported_year: 2014, reported_month: 9, reported_day: nil, location_state: "MI", location_city: "Detroid", location_county: nil, location_zip: "48207", location_notes: "42.361031, -83.021302", context: "other", victim_count: 2, victim_animal: false, victim_notes: "", abuse_force: true, abuse_search: false, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 19, officer_count: 2, officer_multiple_incident: nil},
  {uuid: "01aa2f69-8221-4faf-ab96-876f3625fc9f", incident_summary: "Officer has sex with 15-year-old girl while on duty. Girl was in the police explorers program.", incident_year: 2011, incident_month: 5, incident_day: nil, reported_year: 2014, reported_month: 4, reported_day: 15, location_state: "OK", location_city: "Wewoka", location_county: nil, location_zip: "74884", location_notes: "", context: "other", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: true, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 20, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "62fdd289-ea99-4489-ba94-2ef3de0e0570", incident_summary: "Police officer fires his gun through a man's door after a slow speed chase and with no indication that the man had any weapon. Killed 68 year old man.", incident_year: 2014, incident_month: 2, incident_day: nil, reported_year: 2014, reported_month: 2, reported_day: nil, location_state: "SC", location_city: "North Augusta", location_county: nil, location_zip: "298", location_notes: "", context: "traffic-stop", victim_count: 1, victim_animal: false, victim_notes: "Earnest Satterwhite", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 21, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "30481741-c278-4236-be42-e3bc472f5f40", incident_summary: "Man drives his car into a ditch and police respond by ticketing him, threatening physical violence, and eventually punch the man in the face. Then try to confiscate the video evidence.", incident_year: 2014, incident_month: 3, incident_day: 17, reported_year: 2014, reported_month: 9, reported_day: 23, location_state: "MD", location_city: "Mt. Rainier", location_county: nil, location_zip: "20712", location_notes: "", context: "traffic-stop", victim_count: nil, victim_animal: false, victim_notes: "Tunde Adeyale", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: true, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 22, officer_count: 2, officer_multiple_incident: nil},
  {uuid: "b9c263e2-2128-4d7e-8a89-1a837c773477", incident_summary: "Cops pull over a car without cause, claim that a drug dog alerted on their vehicle, and seized cash that was in the vehicle.", incident_year: 2013, incident_month: 4, incident_day: 15, reported_year: 2014, reported_month: 9, reported_day: 30, location_state: "IA", location_city: "", location_county: nil, location_zip: "", location_notes: "", context: "911", victim_count: 2, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: true, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "Pulled over for failing to signal, but dashcam shows that the car did signal. Also claimed that a dog hit on the car, but that was not seen in the video either. Then arrested the men for having small flecks of weed and used civil forfeiture to take their cash.", outcome_dollars: nil, department_id: 23, officer_count: 2, officer_multiple_incident: nil},
  {uuid: "7aa6c849-a621-40cf-b632-3102f8528c33", incident_summary: "Police officer responds to a 911 call about an unresponsive woman. He proceeds to give her more alcohol, tie her up, and force her to commit sex acts. Then he lied to the FBI about it. He wasn't charged for the sexual assault.", incident_year: 2013, incident_month: 11, incident_day: nil, reported_year: 2014, reported_month: 10, reported_day: 1, location_state: "LA", location_city: "Sorrento", location_county: nil, location_zip: "70778", location_notes: "", context: "911", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: true, abuse_intimidation: true, abuse_sexual: true, abuse_restrained: true, abuse_notes: "Theriot carried the woman into his office and tied her to a chair with a belt.  He then admits to removing he clothes and forcing her to perform sexual acts while she was barely conscious.  Theriot then left the woman tied to the chair in his office while he attended a meeting in another part of the building. After the encounter, Theriot continued to call the woman to harass her, and ask her to get together with him again.", outcome_dollars: nil, department_id: 24, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "128bf01c-584f-475e-960d-c7025503da72", incident_summary: "Officers arrest a woman for recording them and charge her with resisting arrest. Jury acquits.", incident_year: 2013, incident_month: 1, incident_day: 23, reported_year: 2014, reported_month: 10, reported_day: 1, location_state: "IL", location_city: "Naperville", location_county: nil, location_zip: "605", location_notes: "", context: "other", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 25, officer_count: 3, officer_multiple_incident: nil},
  {uuid: "fc51c3b5-9a3b-4e48-ade1-9268680f9b3b", incident_summary: "Roberts stopped a 36-year-old woman on Interstate 44 in Creek County just after 2 p.m. June 15, offered her $20 for a lap dance and then instructed her “to use a U-Haul truck to move, so he could stop her and they could have sexual intercourse in the back” of the truck, an affidavit states. the 16-year trooper had turned off his dash camera and microphone during all three of the alleged sexual assaults", incident_year: 2014, incident_month: 6, incident_day: 15, reported_year: 2014, reported_month: 10, reported_day: 1, location_state: "OK", location_city: "", location_county: nil, location_zip: "", location_notes: "", context: "traffic-stop", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: true, abuse_restrained: false, abuse_notes: "Roberts stopped a 36-year-old woman on Interstate 44 in Creek County just after 2 p.m. June 15, offered her $20 for a lap dance and then instructed her “to use a U-Haul truck to move, so he could stop her and they could have sexual intercourse in the back” of the truck, an affidavit states. the 16-year trooper had turned off his dash camera and microphone during all three of the alleged sexual assaults", outcome_dollars: nil, department_id: 26, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "98dfc32f-ee65-4bb8-8ab9-a82e3648bd80", incident_summary: "Roberts allegedly pulled over a 22-year-old woman on July 8 for a traffic violation and asked her “what she would do for that amount of money,” according to the affidavit. It says Roberts placed the woman in his patrol vehicle, drove her to a secluded location and had her give him oral sex. the 16-year trooper had turned off his dash camera and microphone during all three of the alleged sexual assaults", incident_year: 2014, incident_month: 7, incident_day: 8, reported_year: 2014, reported_month: 10, reported_day: 1, location_state: "OK", location_city: "", location_county: nil, location_zip: "", location_notes: "", context: "911", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: true, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 26, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "7cca1f46-c83a-4cee-99f1-998c2c55de46", incident_summary: "On July 22, Roberts allegedly pulled over a woman who had warrants out for her arrest and informed her that he “didn’t need to take her to jail or write her a ticket, but he needed some convincing.” He eventually drove her to a secluded location, where the rape occurred. the 16-year trooper had turned off his dash camera and microphone during all three of the alleged sexual assaults", incident_year: 2014, incident_month: 7, incident_day: 22, reported_year: 2014, reported_month: 10, reported_day: 1, location_state: "OK", location_city: "", location_county: nil, location_zip: "", location_notes: "", context: "traffic-stop", victim_count: nil, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: true, abuse_intimidation: false, abuse_sexual: true, abuse_restrained: false, abuse_notes: "", outcome_dollars: nil, department_id: 26, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "090ffd8b-9a92-48b5-a422-a8ea88343eaa", incident_summary: "Cop punches and kicks handcuffed man", incident_year: 2014, incident_month: 6, incident_day: nil, reported_year: 2014, reported_month: 10, reported_day: nil, location_state: "FL", location_city: "Orlando", location_county: nil, location_zip: "", location_notes: "", context: "unknown", victim_count: 1, victim_animal: false, victim_notes: "Refus Holloway", abuse_force: true, abuse_search: false, abuse_misconduct: false, abuse_intimidation: false, abuse_sexual: false, abuse_restrained: true, abuse_notes: "", outcome_dollars: nil, department_id: 27, officer_count: 1, officer_multiple_incident: nil},
  {uuid: "fcf7efe8-e3bf-47ca-b60f-6e3ddbd1834e", incident_summary: "Officers threatens a woman with false arrest if she does not perform sex acts.", incident_year: 2014, incident_month: 3, incident_day: nil, reported_year: 2014, reported_month: 10, reported_day: nil, location_state: "TX", location_city: "Seabrook", location_county: nil, location_zip: "77586", location_notes: "", context: "other", victim_count: 1, victim_animal: false, victim_notes: "", abuse_force: false, abuse_search: false, abuse_misconduct: false, abuse_intimidation: true, abuse_sexual: true, abuse_restrained: false, abuse_notes: "The woman told authorities that Krumrey approached her in the parking lot of her apartment complex, while in uniform, and accused her of driving drunk. She claims Krumrey told her he could take her to jail or they could \"work it out.\" She says he followed her to her apartment and demanded sexual acts. Krumrey reportedly told police that he was having an affair with the woman.", outcome_dollars: nil, department_id: 28, officer_count: 1, officer_multiple_incident: nil}
])
ActsAsTaggableOn::Tagging.create!([
  {tag_id: 1, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 2, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 4, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 5, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 6, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 7, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 7, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "internal_outcome_variety"},
  {tag_id: 7, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 7, taggable_id: 1, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 7, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 7, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 8, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 9, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 10, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_intimidation_variety"},
  {tag_id: 5, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 11, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 3, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 12, taggable_id: 2, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 13, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 14, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 15, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_intimidation_variety"},
  {tag_id: 16, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 17, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "department_statement_variety"},
  {tag_id: 1, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 18, taggable_id: 3, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 19, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 20, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 13, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 9, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 5, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 6, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 21, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 16, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 7, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "internal_outcome_variety"},
  {tag_id: 1, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 4, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 19, taggable_id: 5, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 3, taggable_id: 5, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 4, taggable_id: 5, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 6, taggable_id: 5, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 1, taggable_id: 5, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 5, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 7, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 7, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 7, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 9, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 22, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 14, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 5, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 23, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 11, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 16, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 24, taggable_id: 6, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 1, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 25, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 26, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 27, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 22, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 5, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 6, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 21, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 7, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 7, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 7, taggable_id: 12, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 19, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 28, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 29, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 30, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_search_variety"},
  {tag_id: 6, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 1, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 37, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 31, taggable_id: 38, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 38, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 26, taggable_id: 38, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 32, taggable_id: 38, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 3, taggable_id: 38, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 13, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 33, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_sexual_variety"},
  {tag_id: 5, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 11, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 34, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 24, taggable_id: 39, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 19, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 28, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 25, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 13, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 29, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 35, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_search_variety"},
  {tag_id: 36, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 10, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_intimidation_variety"},
  {tag_id: 6, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 3, taggable_id: 40, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 37, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 38, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 28, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 9, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 35, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_search_variety"},
  {tag_id: 36, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 6, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 21, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 39, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "internal_outcome_variety"},
  {tag_id: 1, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 13, taggable_id: 41, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 1, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 3, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 4, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 9, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 6, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 40, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 39, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "internal_outcome_variety"},
  {tag_id: 3, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 13, taggable_id: 42, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 19, taggable_id: 43, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 2, taggable_id: 43, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 13, taggable_id: 43, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 9, taggable_id: 43, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 36, taggable_id: 43, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 5, taggable_id: 43, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 6, taggable_id: 43, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 19, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 28, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 9, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 36, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 39, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "internal_outcome_variety"},
  {tag_id: 1, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 44, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 38, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 13, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 41, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_sexual_variety"},
  {tag_id: 5, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 11, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 1, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 18, taggable_id: 45, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 19, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 42, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 3, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 8, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 43, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 11, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 32, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 46, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 19, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 3, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 9, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 10, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_intimidation_variety"},
  {tag_id: 44, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_intimidation_variety"},
  {tag_id: 5, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 6, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 3, taggable_id: 47, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 1, taggable_id: 48, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 3, taggable_id: 48, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 30, taggable_id: 48, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_search_variety"},
  {tag_id: 45, taggable_id: 48, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 6, taggable_id: 48, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 46, taggable_id: 48, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "department_statement_variety"},
  {tag_id: 3, taggable_id: 48, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 13, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 22, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 15, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_intimidation_variety"},
  {tag_id: 33, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_sexual_variety"},
  {tag_id: 5, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 6, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 11, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 34, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 49, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 25, taggable_id: 50, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_age"},
  {tag_id: 13, taggable_id: 50, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 36, taggable_id: 50, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 3, taggable_id: 50, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 13, taggable_id: 51, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 47, taggable_id: 51, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_sexual_variety"},
  {tag_id: 11, taggable_id: 51, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 48, taggable_id: 51, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 51, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 51, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 24, taggable_id: 51, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 13, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 49, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 33, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_sexual_variety"},
  {tag_id: 5, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 11, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 48, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 24, taggable_id: 52, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 13, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 49, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_misconduct_variety"},
  {tag_id: 33, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_sexual_variety"},
  {tag_id: 5, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "physical_outcome_variety"},
  {tag_id: 11, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 34, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 24, taggable_id: 53, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_year"},
  {tag_id: 19, taggable_id: 54, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_race"},
  {tag_id: 3, taggable_id: 54, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 9, taggable_id: 54, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_force_variety"},
  {tag_id: 23, taggable_id: 54, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 1, taggable_id: 54, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 54, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"},
  {tag_id: 13, taggable_id: 55, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "victim_gender"},
  {tag_id: 10, taggable_id: 55, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_intimidation_variety"},
  {tag_id: 33, taggable_id: 55, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "abuse_sexual_variety"},
  {tag_id: 11, taggable_id: 55, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "legal_outcome_variety"},
  {tag_id: 16, taggable_id: 55, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "hr_outcome_variety"},
  {tag_id: 1, taggable_id: 55, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_race"},
  {tag_id: 3, taggable_id: 55, taggable_type: "Incident", tagger_id: nil, tagger_type: nil, context: "officer_gender"}
])
ActsAsTaggableOn::Tag.create!([
  {name: "white", taggings_count: 20},
  {name: "6-12", taggings_count: 2},
  {name: "male", taggings_count: 38},
  {name: "taser", taggings_count: 3},
  {name: "injured", taggings_count: 12},
  {name: "lawsuit", taggings_count: 12},
  {name: "unknown", taggings_count: 13},
  {name: "firearm", taggings_count: 2},
  {name: "unarmed", taggings_count: 9},
  {name: "threats", taggings_count: 4},
  {name: "criminal-charges", taggings_count: 10},
  {name: "10-14", taggings_count: 1},
  {name: "female", taggings_count: 14},
  {name: "falsifying-evidence", taggings_count: 2},
  {name: "harass-stalk", taggings_count: 2},
  {name: "fired", taggings_count: 4},
  {name: "acted-inappropriately", taggings_count: 1},
  {name: "0-4", taggings_count: 2},
  {name: "black", taggings_count: 9},
  {name: "45-54", taggings_count: 1},
  {name: "settlement", taggings_count: 3},
  {name: "false-report", taggings_count: 3},
  {name: "external-investigation", taggings_count: 2},
  {name: "15-19", taggings_count: 5},
  {name: "35-44", taggings_count: 3},
  {name: "other", taggings_count: 2},
  {name: "testilying", taggings_count: 1},
  {name: "18-24", taggings_count: 4},
  {name: "confiscation", taggings_count: 2},
  {name: "vehicle", taggings_count: 2},
  {name: "25-34", taggings_count: 1},
  {name: "paid-suspension", taggings_count: 2},
  {name: "abuse-adult", taggings_count: 5},
  {name: "quit", taggings_count: 3},
  {name: "home", taggings_count: 2},
  {name: "false-arrest", taggings_count: 5},
  {name: "latino", taggings_count: 1},
  {name: "13-17", taggings_count: 2},
  {name: "cleared", taggings_count: 3},
  {name: "fines", taggings_count: 1},
  {name: "abuse-minor", taggings_count: 1},
  {name: "65+", taggings_count: 1},
  {name: "killed", taggings_count: 1},
  {name: "verbal-abuse", taggings_count: 1},
  {name: "civil-forfeit", taggings_count: 1},
  {name: "acted-appropriately", taggings_count: 1},
  {name: "harassment", taggings_count: 1},
  {name: "unpaid-suspension", taggings_count: 2},
  {name: "bribe", taggings_count: 2}
])
Reference.create!([
  {url: "http://abcnews.go.com/blogs/headlines/2012/11/tasered-10-year-old-boy-sues-police/", date_accessed: nil, headline: "Tasered 10-Year-Old Boy Sues Police", org_name: "ABC News", incident_id: 1, publish_date: nil},
  {url: "http://www.elpasotimes.com/latestnews/ci_26611845/jury-convicts-new-mexico-sheriff-heated-traffic-stop", date_accessed: nil, headline: "Jury convicts New Mexico sheriff in heated traffic stop", org_name: "El Paso Times", incident_id: 2, publish_date: nil},
  {url: "http://www.wsmv.com/video?clipId=10595213&autostart=true", date_accessed: nil, headline: "Mt. Juliet Police Officer Fired After Turning Off", org_name: "WSMV", incident_id: 3, publish_date: nil},
  {url: "https://www.bbc.com/news/world-us-canada-29365980", date_accessed: nil, headline: "$1.5m payout for US woman punched by police at roadside", org_name: "BBC News", incident_id: 4, publish_date: nil},
  {url: "http://www.rawstory.com/rs/2014/09/pittsburgh-cops-tased-man-while-he-was-praying-for-his-dead-son-in-er-lawsuit/", date_accessed: nil, headline: "Pittsburgh cops Tased man while he was praying for his dead son in ER: lawsuit", org_name: "Raw Story", incident_id: 5, publish_date: nil},
  {url: "http://www.syracuse.com/news/index.ssf/2014/09/fulton_police_officer_pleads_guilty_in_federal_court_to_assaulting_man_in_custod.html", date_accessed: nil, headline: "Fulton police officer pleads guilty in federal court to assaulting man in custody", org_name: "Syracuse.com", incident_id: 6, publish_date: nil},
  {url: "http://thefreethoughtproject.com/hear-nickel-ride-philly-cops-gave-man-one-tax-payers-giving-490k/#gwrPwrkeLgMLHjba.99", date_accessed: nil, headline: "Ever Hear of a “Nickel Ride”? Philly Cops Gave this Man One, Now Tax-payers are Giving Him $490K Read more at http://thefreethoughtproject.com/hear-nickel-ride-philly-cops-gave-man-one-tax-payers-giving-490k/#SbV5I8qj04LXW6Db.99", org_name: "Free Thought Project", incident_id: 12, publish_date: nil},
  {url: "https://www.techdirt.com/articles/20140921/17412528595/cops-seize-car-when-told-to-get-warrant-tell-owner-thats-what-he-gets-exercising-his-rights.shtml", date_accessed: nil, headline: "Cops Seize Car When Told To Get A Warrant, Tell Owner That's What He Gets For 'Exercising His Rights'", org_name: "Tech Dirt", incident_id: 37, publish_date: nil},
  {url: "http://www.timesargus.com/article/20140920/NEWS03/709209985", date_accessed: nil, headline: "Man claims police seized car illegally", org_name: "Barre Montpelier Times Argus", incident_id: 37, publish_date: nil},
  {url: "http://thefreethoughtproject.com/4-cops-fired-tipping-portable-toilet-man/", date_accessed: nil, headline: "4 Cops Suspended After Being Caught on Video Tipping Over Portable Toilet With Man Inside Read more at http://thefreethoughtproject.com/4-cops-fired-tipping-portable-toilet-man/#WcqxoQA3bHH8GMFA.99", org_name: "Free Thought Project", incident_id: 38, publish_date: nil},
  {url: "https://www.youtube.com/watch?v=bDVJ-RoouY8", date_accessed: nil, headline: "Raw: MPD tips portable toilet to try and capture suspect", org_name: "YouTube", incident_id: 38, publish_date: nil},
  {url: "http://wane.com/2014/09/26/ex-cop-gets-6-years-behind-bars-for-rape/", date_accessed: nil, headline: "Ex-cop gets 6 years behind bars for rape", org_name: "WANE", incident_id: 39, publish_date: nil},
  {url: "http://wane.com/2013/12/05/fwpd-officer-charged-with-rape/", date_accessed: nil, headline: "FWPD officer charged with rape", org_name: "WANE", incident_id: 39, publish_date: nil},
  {url: "http://wane.com/2014/09/05/officer-who-pleaded-guilty-to-rape-resigns/", date_accessed: nil, headline: "Officer who pleaded guilty to rape resigns", org_name: "WANE", incident_id: 39, publish_date: nil},
  {url: "http://rt.com/usa/191636-police-arrest-woman-filming/", date_accessed: nil, headline: "Cops sued for breaking into home, arresting woman for recording their actions (VIDEO)", org_name: "Russia Times", incident_id: 40, publish_date: nil},
  {url: "http://www.nbcphiladelphia.com/news/local/Couple-Sues-Police-Over-Tense-Confrontation-Inside-Collingdale-Home-276875291.html#ixzz3EjIALfZh", date_accessed: nil, headline: "Couple Sues Police Over Tense Confrontation Inside Collingdale Home  Read more: http://www.nbcphiladelphia.com/news/local/Couple-Sues-Police-Over-Tense-Confrontation-Inside-Collingdale-Home-276875291.html#ixzz3ElHla7Y2  Follow us: @nbcphiladelphia on Twitter | nbcphiladelphia on Facebook", org_name: "WCAU NBC 10", incident_id: 40, publish_date: nil},
  {url: "https://www.youtube.com/watch?v=cSi3SpMH8Gg", date_accessed: nil, headline: "Pennsylvania Police Arrest Woman For Filming Them", org_name: "YouTube", incident_id: 40, publish_date: nil},
  {url: "http://blogs.westword.com/latestword/2014/09/martinez_family_lawsuit_jury_award_police_raid.php", date_accessed: nil, headline: "Martinez Family Lawsuit: $1.8 Million Award After Police Raid on Wrong House", org_name: "Denver Westword", incident_id: 41, publish_date: nil},
  {url: "http://blogs.westword.com/latestword/2011/01/martinez_family_lawsuit_beating_denver_police.php", date_accessed: nil, headline: "Martinez family lawsuit: Members of Mexican band say Denver cops mistakenly beat them", org_name: "Denver Westword", incident_id: 41, publish_date: nil},
  {url: "http://www.9news.com/story/news/local/2014/09/28/wrongful-prosecution-mistaken-raid-denver/16409795/", date_accessed: nil, headline: "Denver family gives account of mistaken police raid", org_name: "KUSA-TV", incident_id: 41, publish_date: nil},
  {url: "http://www.kptv.com/story/26658769/jury-awards-man-562k-in-portland-police-excessive-force-lawsuit", date_accessed: nil, headline: "Jury awards man $562K in Portland police excessive force lawsuit", org_name: "Fox 12 Oregon", incident_id: 42, publish_date: nil},
  {url: "http://ftpcontent.worldnow.com/kptv/KPTV/story_pdfs/ppbinternalaffairsreport.pdf", date_accessed: nil, headline: "", org_name: "City of Portland", incident_id: 42, publish_date: nil},
  {url: "http://thefreethoughtproject.com/cops-beat-kidnap-12-yo-girl-front-home-claiming-prostitute/", date_accessed: nil, headline: "When her mother and father came outside after hearing her cries for help she was desperately holding a tree with one arm while plainclothes officers were beating her in the head, neck and throat.", org_name: "Free Thought Project", incident_id: 43, publish_date: nil},
  {url: "http://www.brownsvilleherald.com/news/valley/article_0ed7b62f-f8d3-5ca2-a7f3-a2e03866263b.html?mode=jqm", date_accessed: nil, headline: "Lawsuit: Girl, 12, not prostitute", org_name: "The Brownsville Herald", incident_id: 43, publish_date: nil},
  {url: "http://www.myfoxdetroit.com/story/23365483/update-charges-dropped-against-brothers-in-video-of-questionable-excessive-police-force", date_accessed: nil, headline: "UPDATE: Charges dropped against brothers in video of questionable excessive police force", org_name: "MyFox Detroit", incident_id: 44, publish_date: nil},
  {url: "https://www.youtube.com/watch?v=62bFlzU2Jks", date_accessed: nil, headline: "Two brothers are harassed by police Then one officer gives a shove and ignites a public brawl!", org_name: "Fox 2 Detroit", incident_id: 44, publish_date: nil},
  {url: "http://www.tulsaworld.com/news/crimewatch/former-wewoka-police-officer-accused-of-sexually-assaulting--year/article_25c8b00d-ccd0-55db-b3e4-04536c1bab8d.html", date_accessed: nil, headline: "Former Wewoka police officer accused of sexually assaulting 15-year-old while on duty", org_name: "Tulsa World", incident_id: 45, publish_date: nil},
  {url: "http://www.huffingtonpost.com/2014/09/30/ernest-satterwhite-just-craven_n_5907544.html", date_accessed: nil, headline: "Cop Allegedly Shot Unarmed Man Parked In His Own Driveway", org_name: "Huffington Post", incident_id: 46, publish_date: nil},
  {url: "http://chronicle.augusta.com/news/crime-courts/2014-02-10/police-identify-suspect-high-speed-chase-fatal-shooting", date_accessed: nil, headline: " Police identify suspect in high-speed chase, fatal shooting", org_name: "The Augusta Chronicle", incident_id: 46, publish_date: nil},
  {url: "http://thefreethoughtproject.com/man-knocked-cop-car-stuck-snow/", date_accessed: nil, headline: "This Man’s Car Got Stuck in the Snow, So Cops Show Up and Knock Him Out Read more at http://thefreethoughtproject.com/man-knocked-cop-car-stuck-snow/#p0RYAsYTlx4bqEyo.99", org_name: "The Free Thought Project", incident_id: 47, publish_date: nil},
  {url: "http://www.foxbaltimore.com/news/features/top-stories/stories/police-actions-small-md-town-prompt-multimillion-dollar-lawsuit-32019.shtml", date_accessed: nil, headline: "Police Actions in Small MD Town Prompt Mu...", org_name: "Fox 45 Baltimore", incident_id: 47, publish_date: nil},
  {url: "http://www.desmoinesregister.com/story/news/crime-and-courts/2014/09/30/iowa-state-patrol-cash-seizure-illegal-gamblers-say/16511135/", date_accessed: nil, headline: "Gamblers say cash seizure was illegal", org_name: "The Des Moines Register", incident_id: 48, publish_date: nil},
  {url: "http://thefreethoughtproject.com/probation-police-chief-sexually-assaulted-unconscious-woman-picked-911-call/#5Jw4O0LukcB27IFk.16", date_accessed: nil, headline: "Police Chief Admits to Sexually Assaulting Unconscious Woman on 911 Call, Won’t See 1 Day in Jail", org_name: "The Free Thought Project", incident_id: 49, publish_date: nil},
  {url: "http://www.chicagotribune.com/suburbs/naperville-lisle/chi-jury-gets-naperville-smart-meter-case-20141001-story.html", date_accessed: nil, headline: "Woman found not guilty in Naperville 'smart meter' case", org_name: "Chicago Tribune", incident_id: 50, publish_date: nil},
  {url: "http://www.tulsaworld.com/newshomepage2/oklahoma-state-trooper-accused-of-rape-resigns/article_d3b5a310-fc95-5a89-bbaf-ba8009e6f70d.html", date_accessed: nil, headline: "Oklahoma state trooper accused of rape resigns", org_name: "Tulsa World", incident_id: 51, publish_date: nil},
  {url: "http://www.tulsaworld.com/newshomepage2/oklahoma-state-trooper-accused-of-rape-resigns/article_d3b5a310-fc95-5a89-bbaf-ba8009e6f70d.html", date_accessed: nil, headline: "Oklahoma state trooper accused of rape resigns", org_name: "Tulsa World", incident_id: 52, publish_date: nil},
  {url: "http://www.tulsaworld.com/newshomepage2/oklahoma-state-trooper-accused-of-rape-resigns/article_d3b5a310-fc95-5a89-bbaf-ba8009e6f70d.html", date_accessed: nil, headline: "Oklahoma state trooper accused of rape resigns", org_name: "Tulsa World", incident_id: 53, publish_date: nil},
  {url: "http://www.wftv.com/news/news/local/state-attorney-investigates-opd-officer-after-body/nhbmQ/?ecmp=wftv_social_twitter_sfp", date_accessed: nil, headline: "State Attorney investigates OPD officer after bodycam video of alleged beating surfaces", org_name: "WFTV Channel 9", incident_id: 54, publish_date: nil},
  {url: "http://abc13.com/news/seabrook-cop-accused-of-sexual-assault/335542/", date_accessed: nil, headline: "SEABROOK COP ACCUSED OF DEMANDING SEX TO HELP WOMAN AVOID JAIL", org_name: "KTRK-TV Houston", incident_id: 55, publish_date: nil}
])
